spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.punshub.top/realms/tmdt
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: ${app.cors.allowed-origin-patterns}
            allowedMethods: GET,POST,PUT,DELETE,OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0
        - id: category-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - StripPrefix=0
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/products/**
          filters:
            - StripPrefix=0
        - id: order-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=0
        - id: cart-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=0
        # Ví dụ về routing cho các service khác:
        # - id: product-service
        #   uri: http://localhost:8082
        #   predicates:
        #     - Path=/api/v1/products/**
        #   filters:
        #     - StripPrefix=0
        # - id: order-service
        #   uri: http://localhost:8083
        #   predicates:
        #     - Path=/api/v1/orders/**
        #   filters:
        #     - StripPrefix=0
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

app:
  cors:
    allowed-origin-patterns: http://localhost:*,https://*.localhost:*
  auth:
    token-validation-url: http://localhost:8081/api/v1/auth/token/validate
