spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: ${app.cors.allowed-origin-patterns}
            allowedMethods: GET,POST,PUT,DELETE,OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
      routes:
        - id: admin-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - StripPrefix=0

        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0

        - id: category-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - StripPrefix=0

        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/products/**
          filters:
            - StripPrefix=0

        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - StripPrefix=0

        - id: order-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=0

        - id: report-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/report/**
          filters:
            - StripPrefix=0

        # Cart service must be at last
        - id: cart-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=0

app:
  cors:
    allowed-origin-patterns: http://localhost:*,https://*.localhost:*
  auth:
    #token-validation-url: http://localhost:8081/api/v1/auth/token/validate
    token-validation-url: https://auth.punshub.top/realms/tmdt/protocol/openid-connect/userinfo
  # Service URLs for dev environment
  services:
    admin-service: http://localhost:8087
    authentication-service: http://localhost:8081
    cart-service: http://localhost:8086
    category-service: http://localhost:8082
    order-service: http://localhost:8085
    payment-service: http://localhost:8084
    product-service: http://localhost:8083
    report-service: http://localhost:8088
