spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: ${app.cors.allowed-origin-patterns}
            allowedMethods: GET,POST,PUT,DELETE,OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0
        # Add more service routes as needed

server:
  port: 8080

app:
  cors:
    allowed-origin-patterns: http://localhost:[*],https://*.localhost:[*]
  auth:
    token-validation-url: http://localhost:8081/api/v1/token/validate
