spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.punshub.top/realms/tmdt
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

logging:
  level:
    root: off
    org.springframework: info
    g5.kttkpm: info
    web: debug
