spring:
  application:
    name: payment-service
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username: admin
    password: sapassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8084

payos:
  client-id: abcd
  api-key: abcd
  checksum-key: abcd

order-service:
  notification-url: http://localhost:8085/api/v1/orders
