spring:
  application:
    name: authentication-service
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: tmdt-back-end
            client-secret: TYwKjdo1iRpwhMJfaWCqjN46ro0eNG8W
            scope: openid email profile phone roles
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: https://auth.punshub.top/realms/tmdt
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.punshub.top/realms/tmdt/protocol/openid-connect/certs
server:
  port: 8081

keycloak:
  auth-server-url: https://auth.punshub.top
  realm: tmdt
  admin-realm: master
  admin-config:
    username: root
    password: root

logging:
  level:
    root: off
    org.springframework: info
    g5.kttkpm: info

resilience4j:
  ratelimiter:
    instances:
      loginRateLimiter:
        limitForPeriod: 5 # 5 requests per second
        limitRefreshPeriod: 10s # 10 seconds
        timeoutDuration: 0 # No timeout
