server:
  port: 8082
spring:
  application:
    name: category-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://punshub.top:5432/category-service
    username: admin
    password: sapassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: off
    org.springframework: info
    g5.kttkpm: info
