spring:
  config:
    activate:
      on-profile: prod

services:
  product-service:
    url: http://api-gateway:8080/api/v1/products
  payment-service:
    url: http://api-gateway:8080/api/v1/payments
  callback:
    success: https://devicer.punshub.top/orders/payment/success?orderId=
    cancel: https://devicer.punshub.top/orders/payment/cancel?orderId=
