spring:
  config:
    activate:
      on-profile: prod

services:
  product-service:
    url: http://api-gateway:8080/api/v1/products
  payment-service:
    url: http://api-gateway:8080/api/v1/payments
