server:
  port: 8085

spring:
  application:
    name: order-service
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://punshub.top:5432/order-service
    username: admin
    password: sapassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

logging:
  level:
    root: off
    org.springframework: info
    g5.kttkpm: info
