server:
  port: 8083
spring:
  application:
    name: product-service
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://
      auto-index-creation: true
      username: admin
      password: sapassword
      database: product-db

services:
  category-service:
    url: http://localhost:8082/api/v1/categories

aws:
  access-key-id: abc
  secret-access-key: abc
  region: ap-southeast-2
  bucket-name: architecture-system-design

resilience4j:
  ratelimiter:
    instances:
      productSearchLimiter:
        limitForPeriod: 5 # 10 requests per second
        limitRefreshPeriod: 1s
        timeoutDuration: 0
